/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddContentRouteImport } from './routes/add-content'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as StoryMapRouteImport } from './routes/story-map'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddContentRoute = AddContentRouteImport.update({
  id: '/add-content',
  path: '/add-content',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryMapRoute = StoryMapRouteImport.update({
  id: '/story-map',
  path: '/story-map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-content': typeof AddContentRoute
  '/library': typeof LibraryRoute
  '/plan': typeof PlanRoute
  '/story-map': typeof StoryMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-content': typeof AddContentRoute
  '/library': typeof LibraryRoute
  '/plan': typeof PlanRoute
  '/story-map': typeof StoryMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-content': typeof AddContentRoute
  '/library': typeof LibraryRoute
  '/plan': typeof PlanRoute
  '/story-map': typeof StoryMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-content' | '/library' | '/plan' | '/story-map'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-content' | '/library' | '/plan' | '/story-map'
  id: '__root__' | '/' | '/add-content' | '/library' | '/plan' | '/story-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddContentRoute: typeof AddContentRoute
  LibraryRoute: typeof LibraryRoute
  PlanRoute: typeof PlanRoute
  StoryMapRoute: typeof StoryMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-content': {
      id: '/add-content'
      path: '/add-content'
      fullPath: '/add-content'
      preLoaderRoute: typeof AddContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-map': {
      id: '/story-map'
      path: '/story-map'
      fullPath: '/story-map'
      preLoaderRoute: typeof StoryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddContentRoute: AddContentRoute,
  LibraryRoute: LibraryRoute,
  PlanRoute: PlanRoute,
  StoryMapRoute: StoryMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
