/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddContentRouteImport } from './routes/add-content'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as ImportYoutubeRouteImport } from './routes/import-youtube'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StoryMapRouteImport } from './routes/story-map'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiContentLibraryRouteImport } from './routes/api/content-library'
import { Route as ApiFoundationRouteImport } from './routes/api/foundation'
import { Route as ApiOnboardingRouteImport } from './routes/api/onboarding'
import { Route as ApiPlanContentRouteImport } from './routes/api/plan-content'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiStoryMapRouteImport } from './routes/api/story-map'
import { Route as ApiAuthUsernameLoginRouteImport } from './routes/api/auth/username-login'
import { Route as ApiDevExtractTestRouteImport } from './routes/api/dev/extract-test'
import { Route as ApiDevSaveContentTestRouteImport } from './routes/api/dev/save-content-test'
import { Route as ApiDevSearchDnaTestRouteImport } from './routes/api/dev/search-dna-test'
import { Route as ApiDevStoryIntelligenceTestRouteImport } from './routes/api/dev/story-intelligence-test'
import { Route as ApiDevSupabaseTestRouteImport } from './routes/api/dev/supabase-test'
import { Route as ApiYoutubeChannelRouteImport } from './routes/api/youtube/channel'
import { Route as ApiYoutubeImportRouteImport } from './routes/api/youtube/import'
import { Route as ApiYoutubeImportedRouteImport } from './routes/api/youtube/imported'
import { Route as ApiYoutubePlaylistVideosRouteImport } from './routes/api/youtube/playlist-videos'
import { Route as ApiYoutubePlaylistsRouteImport } from './routes/api/youtube/playlists'
import { Route as ApiYoutubeVideosRouteImport } from './routes/api/youtube/videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddContentRoute = AddContentRouteImport.update({
  id: '/add-content',
  path: '/add-content',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportYoutubeRoute = ImportYoutubeRouteImport.update({
  id: '/import-youtube',
  path: '/import-youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryMapRoute = StoryMapRouteImport.update({
  id: '/story-map',
  path: '/story-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentLibraryRoute = ApiContentLibraryRouteImport.update({
  id: '/api/content-library',
  path: '/api/content-library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoundationRoute = ApiFoundationRouteImport.update({
  id: '/api/foundation',
  path: '/api/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingRoute = ApiOnboardingRouteImport.update({
  id: '/api/onboarding',
  path: '/api/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanContentRoute = ApiPlanContentRouteImport.update({
  id: '/api/plan-content',
  path: '/api/plan-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryMapRoute = ApiStoryMapRouteImport.update({
  id: '/api/story-map',
  path: '/api/story-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUsernameLoginRoute = ApiAuthUsernameLoginRouteImport.update({
  id: '/api/auth/username-login',
  path: '/api/auth/username-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevExtractTestRoute = ApiDevExtractTestRouteImport.update({
  id: '/api/dev/extract-test',
  path: '/api/dev/extract-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSaveContentTestRoute = ApiDevSaveContentTestRouteImport.update({
  id: '/api/dev/save-content-test',
  path: '/api/dev/save-content-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSearchDnaTestRoute = ApiDevSearchDnaTestRouteImport.update({
  id: '/api/dev/search-dna-test',
  path: '/api/dev/search-dna-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevStoryIntelligenceTestRoute =
  ApiDevStoryIntelligenceTestRouteImport.update({
    id: '/api/dev/story-intelligence-test',
    path: '/api/dev/story-intelligence-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevSupabaseTestRoute = ApiDevSupabaseTestRouteImport.update({
  id: '/api/dev/supabase-test',
  path: '/api/dev/supabase-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeChannelRoute = ApiYoutubeChannelRouteImport.update({
  id: '/api/youtube/channel',
  path: '/api/youtube/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeImportRoute = ApiYoutubeImportRouteImport.update({
  id: '/api/youtube/import',
  path: '/api/youtube/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeImportedRoute = ApiYoutubeImportedRouteImport.update({
  id: '/api/youtube/imported',
  path: '/api/youtube/imported',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubePlaylistVideosRoute =
  ApiYoutubePlaylistVideosRouteImport.update({
    id: '/api/youtube/playlist-videos',
    path: '/api/youtube/playlist-videos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiYoutubePlaylistsRoute = ApiYoutubePlaylistsRouteImport.update({
  id: '/api/youtube/playlists',
  path: '/api/youtube/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeVideosRoute = ApiYoutubeVideosRouteImport.update({
  id: '/api/youtube/videos',
  path: '/api/youtube/videos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-content': typeof AddContentRoute
  '/foundation': typeof FoundationRoute
  '/import-youtube': typeof ImportYoutubeRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/story-map': typeof StoryMapRoute
  '/api/content': typeof ApiContentRoute
  '/api/content-library': typeof ApiContentLibraryRoute
  '/api/foundation': typeof ApiFoundationRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/plan-content': typeof ApiPlanContentRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/story-map': typeof ApiStoryMapRoute
  '/api/auth/username-login': typeof ApiAuthUsernameLoginRoute
  '/api/dev/extract-test': typeof ApiDevExtractTestRoute
  '/api/dev/save-content-test': typeof ApiDevSaveContentTestRoute
  '/api/dev/search-dna-test': typeof ApiDevSearchDnaTestRoute
  '/api/dev/story-intelligence-test': typeof ApiDevStoryIntelligenceTestRoute
  '/api/dev/supabase-test': typeof ApiDevSupabaseTestRoute
  '/api/youtube/channel': typeof ApiYoutubeChannelRoute
  '/api/youtube/import': typeof ApiYoutubeImportRoute
  '/api/youtube/imported': typeof ApiYoutubeImportedRoute
  '/api/youtube/playlist-videos': typeof ApiYoutubePlaylistVideosRoute
  '/api/youtube/playlists': typeof ApiYoutubePlaylistsRoute
  '/api/youtube/videos': typeof ApiYoutubeVideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-content': typeof AddContentRoute
  '/foundation': typeof FoundationRoute
  '/import-youtube': typeof ImportYoutubeRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/story-map': typeof StoryMapRoute
  '/api/content': typeof ApiContentRoute
  '/api/content-library': typeof ApiContentLibraryRoute
  '/api/foundation': typeof ApiFoundationRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/plan-content': typeof ApiPlanContentRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/story-map': typeof ApiStoryMapRoute
  '/api/auth/username-login': typeof ApiAuthUsernameLoginRoute
  '/api/dev/extract-test': typeof ApiDevExtractTestRoute
  '/api/dev/save-content-test': typeof ApiDevSaveContentTestRoute
  '/api/dev/search-dna-test': typeof ApiDevSearchDnaTestRoute
  '/api/dev/story-intelligence-test': typeof ApiDevStoryIntelligenceTestRoute
  '/api/dev/supabase-test': typeof ApiDevSupabaseTestRoute
  '/api/youtube/channel': typeof ApiYoutubeChannelRoute
  '/api/youtube/import': typeof ApiYoutubeImportRoute
  '/api/youtube/imported': typeof ApiYoutubeImportedRoute
  '/api/youtube/playlist-videos': typeof ApiYoutubePlaylistVideosRoute
  '/api/youtube/playlists': typeof ApiYoutubePlaylistsRoute
  '/api/youtube/videos': typeof ApiYoutubeVideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-content': typeof AddContentRoute
  '/foundation': typeof FoundationRoute
  '/import-youtube': typeof ImportYoutubeRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/story-map': typeof StoryMapRoute
  '/api/content': typeof ApiContentRoute
  '/api/content-library': typeof ApiContentLibraryRoute
  '/api/foundation': typeof ApiFoundationRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/plan-content': typeof ApiPlanContentRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/story-map': typeof ApiStoryMapRoute
  '/api/auth/username-login': typeof ApiAuthUsernameLoginRoute
  '/api/dev/extract-test': typeof ApiDevExtractTestRoute
  '/api/dev/save-content-test': typeof ApiDevSaveContentTestRoute
  '/api/dev/search-dna-test': typeof ApiDevSearchDnaTestRoute
  '/api/dev/story-intelligence-test': typeof ApiDevStoryIntelligenceTestRoute
  '/api/dev/supabase-test': typeof ApiDevSupabaseTestRoute
  '/api/youtube/channel': typeof ApiYoutubeChannelRoute
  '/api/youtube/import': typeof ApiYoutubeImportRoute
  '/api/youtube/imported': typeof ApiYoutubeImportedRoute
  '/api/youtube/playlist-videos': typeof ApiYoutubePlaylistVideosRoute
  '/api/youtube/playlists': typeof ApiYoutubePlaylistsRoute
  '/api/youtube/videos': typeof ApiYoutubeVideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-content'
    | '/foundation'
    | '/import-youtube'
    | '/library'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/reset-password'
    | '/story-map'
    | '/api/content'
    | '/api/content-library'
    | '/api/foundation'
    | '/api/onboarding'
    | '/api/plan-content'
    | '/api/profile'
    | '/api/story-map'
    | '/api/auth/username-login'
    | '/api/dev/extract-test'
    | '/api/dev/save-content-test'
    | '/api/dev/search-dna-test'
    | '/api/dev/story-intelligence-test'
    | '/api/dev/supabase-test'
    | '/api/youtube/channel'
    | '/api/youtube/import'
    | '/api/youtube/imported'
    | '/api/youtube/playlist-videos'
    | '/api/youtube/playlists'
    | '/api/youtube/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-content'
    | '/foundation'
    | '/import-youtube'
    | '/library'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/reset-password'
    | '/story-map'
    | '/api/content'
    | '/api/content-library'
    | '/api/foundation'
    | '/api/onboarding'
    | '/api/plan-content'
    | '/api/profile'
    | '/api/story-map'
    | '/api/auth/username-login'
    | '/api/dev/extract-test'
    | '/api/dev/save-content-test'
    | '/api/dev/search-dna-test'
    | '/api/dev/story-intelligence-test'
    | '/api/dev/supabase-test'
    | '/api/youtube/channel'
    | '/api/youtube/import'
    | '/api/youtube/imported'
    | '/api/youtube/playlist-videos'
    | '/api/youtube/playlists'
    | '/api/youtube/videos'
  id:
    | '__root__'
    | '/'
    | '/add-content'
    | '/foundation'
    | '/import-youtube'
    | '/library'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/reset-password'
    | '/story-map'
    | '/api/content'
    | '/api/content-library'
    | '/api/foundation'
    | '/api/onboarding'
    | '/api/plan-content'
    | '/api/profile'
    | '/api/story-map'
    | '/api/auth/username-login'
    | '/api/dev/extract-test'
    | '/api/dev/save-content-test'
    | '/api/dev/search-dna-test'
    | '/api/dev/story-intelligence-test'
    | '/api/dev/supabase-test'
    | '/api/youtube/channel'
    | '/api/youtube/import'
    | '/api/youtube/imported'
    | '/api/youtube/playlist-videos'
    | '/api/youtube/playlists'
    | '/api/youtube/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddContentRoute: typeof AddContentRoute
  FoundationRoute: typeof FoundationRoute
  ImportYoutubeRoute: typeof ImportYoutubeRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StoryMapRoute: typeof StoryMapRoute
  ApiContentRoute: typeof ApiContentRoute
  ApiContentLibraryRoute: typeof ApiContentLibraryRoute
  ApiFoundationRoute: typeof ApiFoundationRoute
  ApiOnboardingRoute: typeof ApiOnboardingRoute
  ApiPlanContentRoute: typeof ApiPlanContentRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiStoryMapRoute: typeof ApiStoryMapRoute
  ApiAuthUsernameLoginRoute: typeof ApiAuthUsernameLoginRoute
  ApiDevExtractTestRoute: typeof ApiDevExtractTestRoute
  ApiDevSaveContentTestRoute: typeof ApiDevSaveContentTestRoute
  ApiDevSearchDnaTestRoute: typeof ApiDevSearchDnaTestRoute
  ApiDevStoryIntelligenceTestRoute: typeof ApiDevStoryIntelligenceTestRoute
  ApiDevSupabaseTestRoute: typeof ApiDevSupabaseTestRoute
  ApiYoutubeChannelRoute: typeof ApiYoutubeChannelRoute
  ApiYoutubeImportRoute: typeof ApiYoutubeImportRoute
  ApiYoutubeImportedRoute: typeof ApiYoutubeImportedRoute
  ApiYoutubePlaylistVideosRoute: typeof ApiYoutubePlaylistVideosRoute
  ApiYoutubePlaylistsRoute: typeof ApiYoutubePlaylistsRoute
  ApiYoutubeVideosRoute: typeof ApiYoutubeVideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-content': {
      id: '/add-content'
      path: '/add-content'
      fullPath: '/add-content'
      preLoaderRoute: typeof AddContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-youtube': {
      id: '/import-youtube'
      path: '/import-youtube'
      fullPath: '/import-youtube'
      preLoaderRoute: typeof ImportYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-map': {
      id: '/story-map'
      path: '/story-map'
      fullPath: '/story-map'
      preLoaderRoute: typeof StoryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content-library': {
      id: '/api/content-library'
      path: '/api/content-library'
      fullPath: '/api/content-library'
      preLoaderRoute: typeof ApiContentLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/foundation': {
      id: '/api/foundation'
      path: '/api/foundation'
      fullPath: '/api/foundation'
      preLoaderRoute: typeof ApiFoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding': {
      id: '/api/onboarding'
      path: '/api/onboarding'
      fullPath: '/api/onboarding'
      preLoaderRoute: typeof ApiOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan-content': {
      id: '/api/plan-content'
      path: '/api/plan-content'
      fullPath: '/api/plan-content'
      preLoaderRoute: typeof ApiPlanContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story-map': {
      id: '/api/story-map'
      path: '/api/story-map'
      fullPath: '/api/story-map'
      preLoaderRoute: typeof ApiStoryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/username-login': {
      id: '/api/auth/username-login'
      path: '/api/auth/username-login'
      fullPath: '/api/auth/username-login'
      preLoaderRoute: typeof ApiAuthUsernameLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/extract-test': {
      id: '/api/dev/extract-test'
      path: '/api/dev/extract-test'
      fullPath: '/api/dev/extract-test'
      preLoaderRoute: typeof ApiDevExtractTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/save-content-test': {
      id: '/api/dev/save-content-test'
      path: '/api/dev/save-content-test'
      fullPath: '/api/dev/save-content-test'
      preLoaderRoute: typeof ApiDevSaveContentTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/search-dna-test': {
      id: '/api/dev/search-dna-test'
      path: '/api/dev/search-dna-test'
      fullPath: '/api/dev/search-dna-test'
      preLoaderRoute: typeof ApiDevSearchDnaTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/story-intelligence-test': {
      id: '/api/dev/story-intelligence-test'
      path: '/api/dev/story-intelligence-test'
      fullPath: '/api/dev/story-intelligence-test'
      preLoaderRoute: typeof ApiDevStoryIntelligenceTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/supabase-test': {
      id: '/api/dev/supabase-test'
      path: '/api/dev/supabase-test'
      fullPath: '/api/dev/supabase-test'
      preLoaderRoute: typeof ApiDevSupabaseTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/channel': {
      id: '/api/youtube/channel'
      path: '/api/youtube/channel'
      fullPath: '/api/youtube/channel'
      preLoaderRoute: typeof ApiYoutubeChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/import': {
      id: '/api/youtube/import'
      path: '/api/youtube/import'
      fullPath: '/api/youtube/import'
      preLoaderRoute: typeof ApiYoutubeImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/imported': {
      id: '/api/youtube/imported'
      path: '/api/youtube/imported'
      fullPath: '/api/youtube/imported'
      preLoaderRoute: typeof ApiYoutubeImportedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/playlist-videos': {
      id: '/api/youtube/playlist-videos'
      path: '/api/youtube/playlist-videos'
      fullPath: '/api/youtube/playlist-videos'
      preLoaderRoute: typeof ApiYoutubePlaylistVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/playlists': {
      id: '/api/youtube/playlists'
      path: '/api/youtube/playlists'
      fullPath: '/api/youtube/playlists'
      preLoaderRoute: typeof ApiYoutubePlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/videos': {
      id: '/api/youtube/videos'
      path: '/api/youtube/videos'
      fullPath: '/api/youtube/videos'
      preLoaderRoute: typeof ApiYoutubeVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddContentRoute: AddContentRoute,
  FoundationRoute: FoundationRoute,
  ImportYoutubeRoute: ImportYoutubeRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StoryMapRoute: StoryMapRoute,
  ApiContentRoute: ApiContentRoute,
  ApiContentLibraryRoute: ApiContentLibraryRoute,
  ApiFoundationRoute: ApiFoundationRoute,
  ApiOnboardingRoute: ApiOnboardingRoute,
  ApiPlanContentRoute: ApiPlanContentRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiStoryMapRoute: ApiStoryMapRoute,
  ApiAuthUsernameLoginRoute: ApiAuthUsernameLoginRoute,
  ApiDevExtractTestRoute: ApiDevExtractTestRoute,
  ApiDevSaveContentTestRoute: ApiDevSaveContentTestRoute,
  ApiDevSearchDnaTestRoute: ApiDevSearchDnaTestRoute,
  ApiDevStoryIntelligenceTestRoute: ApiDevStoryIntelligenceTestRoute,
  ApiDevSupabaseTestRoute: ApiDevSupabaseTestRoute,
  ApiYoutubeChannelRoute: ApiYoutubeChannelRoute,
  ApiYoutubeImportRoute: ApiYoutubeImportRoute,
  ApiYoutubeImportedRoute: ApiYoutubeImportedRoute,
  ApiYoutubePlaylistVideosRoute: ApiYoutubePlaylistVideosRoute,
  ApiYoutubePlaylistsRoute: ApiYoutubePlaylistsRoute,
  ApiYoutubeVideosRoute: ApiYoutubeVideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
