/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddContentRouteImport } from './routes/add-content'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as StoryMapRouteImport } from './routes/story-map'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiDevExtractTestRouteImport } from './routes/api/dev/extract-test'
import { Route as ApiDevSaveContentTestRouteImport } from './routes/api/dev/save-content-test'
import { Route as ApiDevSearchDnaTestRouteImport } from './routes/api/dev/search-dna-test'
import { Route as ApiDevSupabaseTestRouteImport } from './routes/api/dev/supabase-test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddContentRoute = AddContentRouteImport.update({
  id: '/add-content',
  path: '/add-content',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryMapRoute = StoryMapRouteImport.update({
  id: '/story-map',
  path: '/story-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevExtractTestRoute = ApiDevExtractTestRouteImport.update({
  id: '/api/dev/extract-test',
  path: '/api/dev/extract-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSaveContentTestRoute = ApiDevSaveContentTestRouteImport.update({
  id: '/api/dev/save-content-test',
  path: '/api/dev/save-content-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSearchDnaTestRoute = ApiDevSearchDnaTestRouteImport.update({
  id: '/api/dev/search-dna-test',
  path: '/api/dev/search-dna-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSupabaseTestRoute = ApiDevSupabaseTestRouteImport.update({
  id: '/api/dev/supabase-test',
  path: '/api/dev/supabase-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-content': typeof AddContentRoute
  '/library': typeof LibraryRoute
  '/plan': typeof PlanRoute
  '/story-map': typeof StoryMapRoute
  '/api/content': typeof ApiContentRoute
  '/api/dev/extract-test': typeof ApiDevExtractTestRoute
  '/api/dev/save-content-test': typeof ApiDevSaveContentTestRoute
  '/api/dev/search-dna-test': typeof ApiDevSearchDnaTestRoute
  '/api/dev/supabase-test': typeof ApiDevSupabaseTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-content': typeof AddContentRoute
  '/library': typeof LibraryRoute
  '/plan': typeof PlanRoute
  '/story-map': typeof StoryMapRoute
  '/api/content': typeof ApiContentRoute
  '/api/dev/extract-test': typeof ApiDevExtractTestRoute
  '/api/dev/save-content-test': typeof ApiDevSaveContentTestRoute
  '/api/dev/search-dna-test': typeof ApiDevSearchDnaTestRoute
  '/api/dev/supabase-test': typeof ApiDevSupabaseTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-content': typeof AddContentRoute
  '/library': typeof LibraryRoute
  '/plan': typeof PlanRoute
  '/story-map': typeof StoryMapRoute
  '/api/content': typeof ApiContentRoute
  '/api/dev/extract-test': typeof ApiDevExtractTestRoute
  '/api/dev/save-content-test': typeof ApiDevSaveContentTestRoute
  '/api/dev/search-dna-test': typeof ApiDevSearchDnaTestRoute
  '/api/dev/supabase-test': typeof ApiDevSupabaseTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-content'
    | '/library'
    | '/plan'
    | '/story-map'
    | '/api/content'
    | '/api/dev/extract-test'
    | '/api/dev/save-content-test'
    | '/api/dev/search-dna-test'
    | '/api/dev/supabase-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-content'
    | '/library'
    | '/plan'
    | '/story-map'
    | '/api/content'
    | '/api/dev/extract-test'
    | '/api/dev/save-content-test'
    | '/api/dev/search-dna-test'
    | '/api/dev/supabase-test'
  id:
    | '__root__'
    | '/'
    | '/add-content'
    | '/library'
    | '/plan'
    | '/story-map'
    | '/api/content'
    | '/api/dev/extract-test'
    | '/api/dev/save-content-test'
    | '/api/dev/search-dna-test'
    | '/api/dev/supabase-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddContentRoute: typeof AddContentRoute
  LibraryRoute: typeof LibraryRoute
  PlanRoute: typeof PlanRoute
  StoryMapRoute: typeof StoryMapRoute
  ApiContentRoute: typeof ApiContentRoute
  ApiDevExtractTestRoute: typeof ApiDevExtractTestRoute
  ApiDevSaveContentTestRoute: typeof ApiDevSaveContentTestRoute
  ApiDevSearchDnaTestRoute: typeof ApiDevSearchDnaTestRoute
  ApiDevSupabaseTestRoute: typeof ApiDevSupabaseTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-content': {
      id: '/add-content'
      path: '/add-content'
      fullPath: '/add-content'
      preLoaderRoute: typeof AddContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-map': {
      id: '/story-map'
      path: '/story-map'
      fullPath: '/story-map'
      preLoaderRoute: typeof StoryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/extract-test': {
      id: '/api/dev/extract-test'
      path: '/api/dev/extract-test'
      fullPath: '/api/dev/extract-test'
      preLoaderRoute: typeof ApiDevExtractTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/save-content-test': {
      id: '/api/dev/save-content-test'
      path: '/api/dev/save-content-test'
      fullPath: '/api/dev/save-content-test'
      preLoaderRoute: typeof ApiDevSaveContentTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/search-dna-test': {
      id: '/api/dev/search-dna-test'
      path: '/api/dev/search-dna-test'
      fullPath: '/api/dev/search-dna-test'
      preLoaderRoute: typeof ApiDevSearchDnaTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/supabase-test': {
      id: '/api/dev/supabase-test'
      path: '/api/dev/supabase-test'
      fullPath: '/api/dev/supabase-test'
      preLoaderRoute: typeof ApiDevSupabaseTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddContentRoute: AddContentRoute,
  LibraryRoute: LibraryRoute,
  PlanRoute: PlanRoute,
  StoryMapRoute: StoryMapRoute,
  ApiContentRoute: ApiContentRoute,
  ApiDevExtractTestRoute: ApiDevExtractTestRoute,
  ApiDevSaveContentTestRoute: ApiDevSaveContentTestRoute,
  ApiDevSearchDnaTestRoute: ApiDevSearchDnaTestRoute,
  ApiDevSupabaseTestRoute: ApiDevSupabaseTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
